ebbamåla/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

website/urls.py
from markdownx import urls as markdownx
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import static

from . import views
from .feeds import BookingFeed


app_name = 'website'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('info', views.InfoView.as_view(), name='info'),
    path('trips', views.TripsView.as_view(), name='trips'),
    path('gallery', views.GalleryView.as_view(), name='gallery'),
    path('gallery/<gallery_id>/', views.GalleryView.as_view(), name='photos'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('calendar/<int:year>/<int:month>/', views.CalendarView.as_view(), name='calendar'),
    path('booking', views.BookingView.as_view(), name='booking'),
    path('booking/<int:id>/', views.BookingView.as_view(), name='booking'),
    path('markdownx/', include(markdownx)),
    path('bookings.ics', BookingFeed(), name='feeds'),
    path('<str:name>.pdf', views.PdfView.as_view(), name='pdf'),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [re_path(r'^media/(?P<path>.*)', views.MediaView.as_view(), name='media')]

website/models.py
import logging
import os
import sys
from datetime import datetime
from io import BytesIO

import piexif
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from markdownx.models import MarkdownxField
from PIL import Image

logger = logging.getLogger(__name__)


class Frontpage(models.Model):
    pub_date = models.DateTimeField(editable=False, auto_now=True)
    content = MarkdownxField(verbose_name=_('Content'))

    class Meta:
        verbose_name = _('Frontpage')
        verbose_name_plural = _('Frontpages')
        get_latest_by = "pub_date"

    def __str__(self):
        return "{} ({})".format(_('Frontpage'), self.id)


class PracticalInfo(models.Model):
    pub_date = models.DateTimeField(editable=False, auto_now=True)
    content = MarkdownxField(verbose_name=_('Content'))

    class Meta:
        verbose_name = _('Practical Info')
        verbose_name_plural = _('Practical Info')

    def __str__(self):
        return "{} ({})".format(_('Practical Info'), self.id)


class Trips(models.Model):
    pub_date = models.DateTimeField(editable=False, auto_now=True)
    content = MarkdownxField(verbose_name=_('Content'))

    class Meta:
        verbose_name = _('Tips for Trips')
        verbose_name_plural = _('Tips for Trips')
        get_latest_by = "pub_date"

    def __str__(self):
        return "{} ({})".format(_('Tips for Trips'), self.id)


class HeaderImage(models.Model):
    photo = models.ImageField(upload_to='headers', verbose_name=_('Photo'))
    thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(600, 180)])

    class Meta:
        verbose_name = _('HeaderImage')
        verbose_name_plural = _('HeaderImages')

    def __str__(self):
        return os.path.basename(self.photo.name)


def gallery_path(instance, filename):
    return os.path.join('photos', instance.gallery.slug, filename)


class GalleryPhoto(models.Model):
    photo = models.ImageField(upload_to=gallery_path, verbose_name=_('Photo'))
    description = models.CharField(max_length=500, blank=True, verbose_name=_('Description'))
    thumbnail = ImageSpecField(source='photo',
                               processors=[ResizeToFill(120, 80)])
    date = models.DateTimeField(editable=False,
                                null=True,
                                verbose_name=_('Photo Date'))
    gallery = models.ForeignKey('Gallery', on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Photo')
        verbose_name_plural = _('Photos')
        ordering = ['date']

    def __str__(self):
        return os.path.basename(self.photo.name)

    def save(self, *args, **kwargs):
        img = Image.open(self.photo)
        if 'exif' in img.info:
            exif_dict = piexif.load(img.info['exif'])

            # Read and save original timestamp of picture if available
            if piexif.ExifIFD.DateTimeOriginal in exif_dict['Exif']:
                exif_date = exif_dict['Exif'][piexif.ExifIFD.DateTimeOriginal].decode()
                self.date = timezone.make_aware(datetime.strptime(exif_date, '%Y:%m:%d %H:%M:%S'))

            # Rotate image and change orientation field if required
            if piexif.ImageIFD.Orientation in exif_dict['0th']:
                orientation = exif_dict['0th'][piexif.ImageIFD.Orientation]
                if orientation not in range(1, 9):
                    logger.warning('Unexpected orientation: {}'.format(orientation))
                elif orientation != 1:
                    self._fix_rotation(img, exif_dict)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return self.photo.url

    def _fix_rotation(self, img, exif_dict):
        orientation = exif_dict['0th'][piexif.ImageIFD.Orientation]
        if orientation == 2:
            img = img.transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 3:
            img = img.rotate(180)
        elif orientation == 4:
            img = img.rotate(180).transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 5:
            img = img.rotate(-90, expand=True).transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 6:
            img = img.rotate(-90, expand=True)
        elif orientation == 7:
            img = img.rotate(90, expand=True).transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 8:
            img = img.rotate(90, expand=True)

        exif_dict['0th'][piexif.ImageIFD.Orientation] = 1
        exif_bytes = piexif.dump(exif_dict)
        output = BytesIO()
        img.save(output, format='JPEG', quality=100, exif=exif_bytes)
        output.seek(0)

        self.photo = InMemoryUploadedFile(output,
                                          'ImageField',
                                          '{}.jpg'.format(self.photo.name.split('.')[0]),
                                          'image/jpeg',
                                          sys.getsizeof(output),
                                          None)


class Gallery(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('Title'))
    description = models.CharField(max_length=500, blank=True, verbose_name=_('Description'))
    pub_date = models.DateTimeField(editable=False, auto_now=True)
    slug = models.SlugField(unique=True, editable=False)

    class Meta:
        verbose_name = _('Photo Gallery')
        verbose_name_plural = _('Photo Galleries')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def thumbnail(self):
        return self.galleryphoto_set.order_by('?')[0].thumbnail

    def get_absolute_url(self):
        return reverse('website:photos', kwargs={'gallery_id': self.slug})


class Booking(models.Model):
    start_date = models.DateField(verbose_name=_('Start date'))
    end_date = models.DateField(verbose_name=_('End date'))
    user = models.ForeignKey(User, editable=False, on_delete=models.CASCADE)
    booker = models.CharField(max_length=100, blank=False, verbose_name=_('Booker'))
    description = models.CharField(max_length=500, blank=False, verbose_name=_('Description'))

    class Meta:
        verbose_name = _('Booking')
        verbose_name_plural = _('Bookings')

    def __str__(self):
        return _(f'{self.booker}s booking')

    def get_absolute_url(self):
        return reverse('website:booking', kwargs={'id': self.pk})

website/views.py
import calendar as cal
import datetime
import logging
from io import BytesIO

from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.http import (
    Http404, HttpResponse, HttpResponseRedirect, StreamingHttpResponse,
)
from django.shortcuts import _get_queryset, get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_noop
from django.views import View
from django.views.generic.base import TemplateView
from django_weasyprint.views import WeasyTemplateView
from pypdf import PdfWriter

from .forms import BookingForm
from .models import Booking, Frontpage, Gallery, Trips

logger = logging.getLogger(__name__)


def get_latest_or_404(klass, *args, **kwargs):
    queryset = _get_queryset(klass)
    try:
        return queryset.filter(*args, **kwargs).latest()
    except queryset.model.DoesNotExist:
        raise Http404('No %s matches the given query.' %
                      queryset.model._meta.object_name)


class IndexView(TemplateView):
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['frontpage'] = get_latest_or_404(Frontpage)
        return context


class InfoView(TemplateView):
    template_name = 'website/info.html'
    sections = {
        'travel_guide': {
            'title': gettext_noop('Travel Guide'),
            'orientation': 'portrait',
        },
        'waste_sorting': {
            'title': gettext_noop('Waste Sorting'),
            'orientation': 'landscape',
        },
        'wilderness_bath': {
            'title': gettext_noop('Wilderness Bath'),
            'orientation': 'portrait',
        },
        'wood': {
            'title': gettext_noop('Wood'),
            'orientation': 'potrait',
        },
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sections'] = InfoView.sections
        return context


class TripsView(TemplateView):
    template_name = 'website/trips.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trips'] = get_latest_or_404(Trips)
        return context


class GalleryView(View):

    def get(self, request, gallery_id=None):
        if gallery_id:
            return render(request, 'website/photos.html',
                          {'gallery': Gallery.objects.get(slug=gallery_id)})
        return render(request, 'website/gallery.html',
                      {'galleries': Gallery.objects.all()})


class CalendarView(View):

    def get(self, request, year=None, month=None):
        now = datetime.datetime.now()
        if not year:
            year = now.year
        if not month:
            month = now.month
        if month > 12:
            raise Http404()

        last_day = cal.monthrange(year, month)[1]
        start_date = datetime.date(year, month, 1)
        end_date = datetime.date(year, month, last_day)
        bookings = Booking.objects.filter(start_date__lte=end_date,
                                          end_date__gte=start_date)
        next_month = (year, month + 1) if month < 12 else (year + 1, 1)
        prev_month = (year, month - 1) if month > 1 else (year - 1, 12)
        return render(
            request, 'website/calendar.html', {
                'year': year,
                'month': month,
                'next_month': next_month,
                'prev_month': prev_month,
                'bookings': bookings
            })


class BookingView(View):

    def post(self, request, id=None):
        if id:
            booking = get_object_or_404(Booking, pk=id)
            if 'update' in request.POST:
                if not request.user.is_superuser and request.user != booking.user:
                    raise PermissionDenied
                instance = get_object_or_404(Booking, id=id)
                form = BookingForm(request.user,
                                   request.POST,
                                   instance=instance)
                if form.is_valid():
                    form.save()
                else:
                    return render(request, 'website/edit_booking.html', {
                        'booking': booking,
                        'form': form
                    })
            elif 'delete' in request.POST:
                if not request.user.is_superuser and request.user != booking.user:
                    raise PermissionDenied
                booking.delete()
            else:
                raise SuspiciousOperation
            return HttpResponseRedirect(reverse('website:calendar'))
        else:
            form = BookingForm(request.user, request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('website:calendar'))
            return render(request, 'website/edit_booking.html', {'form': form})

    def get(self, request, id=None):
        if id:
            booking = get_object_or_404(Booking, pk=id)
            if request.user.is_superuser or request.user == booking.user:
                form = BookingForm(request.user,
                                   initial={
                                       'start_date': booking.start_date,
                                       'end_date': booking.end_date,
                                       'booker': booking.booker,
                                       'description': booking.description
                                   })
                return render(request, 'website/edit_booking.html', {
                    'booking': booking,
                    'form': form
                })
            return render(request, 'website/booking.html',
                          {'booking': booking})
        else:
            if all(val in request.GET for val in ['year', 'month', 'day']):
                start_date = datetime.date(int(request.GET['year']),
                                           int(request.GET['month']),
                                           int(request.GET['day']))
            else:
                start_date = datetime.date.today()
            form = BookingForm(request.user,
                               initial={
                                   'start_date':
                                   start_date,
                                   'end_date':
                                   start_date + datetime.timedelta(days=2)
                               })
            return render(request, 'website/edit_booking.html', {'form': form})


class MediaView(View):

    def get(self, request, path):
        response = HttpResponse()
        del response['Content-Type']
        response['X-Accel-Redirect'] = '/protected/media/{}'.format(
            path).encode('utf-8')
        return response


class PdfView(WeasyTemplateView):
    logging.getLogger('fontTools').setLevel(logging.ERROR)
    logging.getLogger('weasyprint').setLevel(logging.ERROR)
    logging.getLogger('django_weasyprint').setLevel(logging.ERROR)
    logging.getLogger('PIL').setLevel(logging.ERROR)

    template_name = 'website/pdf_base.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        name = context['name']
        if name == 'practical_info':
            return self.merged_content(context)
        if name not in InfoView.sections:
            raise Http404
        context.update(InfoView.sections[name])
        return self.render_to_response(context)

    def merged_content(self, context):
        merger = PdfWriter()
        for name, section in InfoView.sections.items():
            context['name'] = name
            context.update(section)
            response = self.render_to_response(context)
            response.render()
            merger.append(BytesIO(response.content))
        bytes_stream = BytesIO()
        merger.write(bytes_stream)
        bytes_stream.seek(0)
        return StreamingHttpResponse(bytes_stream, content_type='application/pdf')

website/templates/website/base.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% load fontawesome_6 %}

<html>
  <head>
    <title>
      Ebbamåla
    </title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% fontawesome_6_static %}
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/flag-icon.min.css' %}"/>
  </head>
  {% block base_content %}
  {% endblock %}
</html>

website/templates/website/booking.html
{% extends 'website/website.html' %}

{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title ml-1">
            {{ booking }}
          </h4>
          <hr/>
        </div>
        <div class="container mb-2">
          <div class="row">
            <div class="col-md-4">
              <p class="font-weight-bold">
                {% trans "Duration" %}
              </p>
            </div>
            <div class="col-md-6">
              {{ booking.start_date }} - {{ booking.end_date }}
            </div>
          </div>
        </div>
        <div class="container mb-2">
          <div class="row">
            <div class="col-md-4">
              <p class="font-weight-bold">
                {% trans "Reserved for" %}
              </p>
            </div>
            <div class="col-md-6">
              <p class="card-text">
                {{ booking.booker }}
              </p>
            </div>
          </div>
        </div>
        <div class="container mb-2">
          <div class="row">
            <div class="col-md-4">
              <p class="font-weight-bold">
                {% trans "Description" %}
              </p>
            </div>
            <div class="col-md-6">
              <p class="card-text">
                {{ booking.description }}
              </p>
            </div>
          </div>
        </div>
        <div class="container mb-2">
          <div class="row">
            <div class="col-md-4">
              <p class="font-weight-bold">
                {% trans "Status" %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/edit_booking.html
{% extends 'website/website.html' %}

{% load fontawesome_6 %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
{% load form_errors %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
  {% get_current_language as LANGUAGE_CODE %}
  {% if LANGUAGE_CODE != 'en' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.{{ LANGUAGE_CODE }}.min.js"></script>
    <script>
     $.fn.datepicker.defaults.language = '{{ LANGUAGE_CODE }}';
    </script>
  {% endif %}
  <script>
   $(function() {
     $('#id_start_date').datepicker({startDate: new Date()});
     $('#id_end_date').datepicker({startDate: new Date()});

     $('#id_start_date').datepicker().on('changeDate', function(e) {
       $('#id_end_date').datepicker('setStartDate', e.date);
     });

     $('#id_end_date').datepicker().on('changeDate', function(e) {
       $('#id_start_date').datepicker('setEndDate', e.date);
     });

     $('#booking_dates').datepicker({
       inputs: [$('#id_start_date'), $('#id_end_date')]
     });
   });
  </script>
{% endblock %}

{% block content %}
  {% form_errors form.non_field_errors %}
{% if booking %}
  <form action="{% url 'website:booking' booking.id %}" method="post" autocomplete="off">
    {% else %}
  <form action="{% url 'website:booking' %}" method="post" autocomplete="off">
{% endif %}
    {% csrf_token %}
    {% form_errors form.start_date.errors %}
    {% form_errors form.end_date.errors %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>
          {% trans "Dates" %}
        </label>
        <div class="input-group" id="booking_dates">
          {{ form.start_date }}
          <span class="input-group-text date-range-splitter">
            {% trans "to" %}
          </span>
          {{ form.end_date }}
        </div>
      </div>
    </div>
    {% form_errors form.description.errors %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="{{ form.user.id_for_label }}">
          {% trans "Reserved for" %}
        </label>
        {{ form.booker }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="{{ form.description.id_for_label }}">
          {% trans "Description" %}
        </label>
        {{ form.description }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        {% if booking %}
        <div class="form-row">
          <div class="form-group col-md">
            <button type="submit" name="update" id="update" class="btn btn-primary">
              {% trans "Update" %}
            </button>
          </div>
          <div class="form-group col-md">
            <button type="button" name="delete" id="delete" class="btn btn-danger" data-toggle="modal" data-target="#delete_booking_dialog">
              {% trans "Delete booking" %}
            </button>
          </div>
        </div>
        {% else %}
        <button type="submit" class="btn btn-primary">
          {% trans "Book" %}
        </button>
        {% endif %}
      </div>
    </div>
  </form>
  {% endblock %}
  {% block endbody %}
  <div class="modal fade" id="delete_booking_dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            {% trans "Delete booking" %}
          </h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>
              &times;
            </span>
          </button>
        </div>
        <div class="modal-body">
          {% blocktrans %}Are you sure you want to delete {{ booking }}?{% endblocktrans %}
        </div>
        <div class="modal-footer">
          <form action="{{ request.path }}" method="post" class="mb-0">
            {% csrf_token %}
            <input type="hidden" name="type" value="delete">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel" %}</button>
            <button type="submit" name="delete" class="btn btn-danger">{% trans "Delete booking" %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

website/templates/website/index.html
{% extends 'website/website.html' %}
{% load markdown %}

{% block content %}
  {{ frontpage.content|markdown|safe }}
{% endblock %}

website/templates/website/info.html
{% extends 'website/website.html' %}

{% load i18n %}
{% load fontawesome_6 %}

{% block content %}
<h1>{% trans 'Practical Information' %}
  <a class="btn btn-link" href="{% url 'website:pdf' name='practical_info' %}">
    <i class="fas fa-file-pdf mr-1"></i>
    {% trans 'Download PDF' %}
  </a>
</h1>
<hr />
{% for name, section in sections.items %}
  <p>
    <h1 id="{{ section.title }}">{% trans section.title %}</a>
      <a class="btn btn-link" href="{% url 'website:pdf' name=name %}">
        <i class="fas fa-file-pdf mr-1"></i>
        {% trans 'Download PDF' %}
      </a>
    </h1>
    {% with template_name='website/'|add:name|add:'.html' %}
      {% include ""|add:template_name %}
    {% endwith %}
  </p>
  {% if not forloop.last %}
  <hr />
  {% endif %}
{% endfor %}
{% endblock %}

website/templates/website/new_booking.html
{% extends 'website/website.html' %}

{% load fontawesome_5 %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
{% load form_errors %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
  {% get_current_language as LANGUAGE_CODE %}
  {% if LANGUAGE_CODE != 'en' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.{{ LANGUAGE_CODE }}.min.js"></script>
    <script>
     $.fn.datepicker.defaults.language = '{{ LANGUAGE_CODE }}';
    </script>
  {% endif %}
  <script>
   $(function() {
     $('#id_start_date').datepicker({startDate: new Date()});
     $('#id_end_date').datepicker({startDate: new Date()});

     $('#id_start_date').datepicker().on('changeDate', function(e) {
       $('#id_end_date').datepicker('setStartDate', e.date);
     });

     $('#id_end_date').datepicker().on('changeDate', function(e) {
       $('#id_start_date').datepicker('setEndDate', e.date);
     });

     $('#booking_dates').datepicker({
       inputs: [$('#id_start_date'), $('#id_end_date')]
     });
   });
  </script>
{% endblock %}

{% block content %}
  {% form_errors form.non_field_errors %}
  <form action="{% url 'website:booking' %}" method="post" autocomplete="off">
    {% csrf_token %}
    {% form_errors form.start_date.errors %}
    {% form_errors form.end_date.errors %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>
          {% trans "Dates" %}
        </label>
        <div class="input-group" id="booking_dates">
          {{ form.start_date }}
          <span class="input-group-text date-range-splitter">
            {% trans "to" %}
          </span>
          {{ form.end_date }}
        </div>
      </div>
    </div>
    {% form_errors form.description.errors %}
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="{{ form.user.id_for_label }}">
          {% trans "Reserved for" %}
        </label>
        {{ form.booker }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="{{ form.description.id_for_label }}">
          {% trans "Description" %}
        </label>
        {{ form.description }}
      </div>
    </div>
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% trans "Book" %}
    </button>
  {% endbuttons %}
  </form>
{% endblock %}

website/templates/website/trips.html
{% extends 'website/website.html' %}
{% load markdown %}

{% block content %}
  <p>
    {{ trips.content|markdown|safe }}
  </p>
{% endblock %}

website/templates/website/website.html
{% extends 'website/base.html' %}

{% load fontawesome_6 %}
{% load activeurl %}
{% load static %}
{% load header_image %}
{% load i18n %}
{% load language_flag %}

{% block head %}
  {{ block.super }}
  <script>
   $(function() {
     $('.dropdown-menu a').click(function (e) {
       e.preventDefault();
       $('#lang-form input[name="language"]').val($(this).data('value'));
       $('#lang-form').submit();
     });
   });
  </script>
{% endblock %}

{% block base_content %}
  <body class="website py-xl-4">
    <div class="container bg-white">
      <div class="card-body">
        <div class="d-flex">
          <h3>
            Ebbamåla
          </h3>
          <div class="dropdown ml-auto mt-2">
            <a href="#" data-toggle="dropdown">
              {% language_flag %}
            </a>
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <div class="dropdown-menu dropdown-menu-right">
              {% for language in languages %}
                <a href="#" class="dropdown-item" data-value="{{ language.code }}">
                  {% language_flag language.code %}
                  <span class="ml-2 mt-3">
                    {{ language.name_local|title }}
                  </span>
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
        <nav class="navbar navbar-light navbar-expand-lg">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
            <span class="navbar-toggler-icon">
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navbar-content">
            {% activeurl %}
            <ul class="navbar-nav mr-auto">
              <li>
                <a class="nav-item nav-link" href="{% url 'website:index' %}">
                  {% trans "Frontpage" %} {% fa6_icon 'home' %}
                </a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'website:info' %}">
                  {% trans "Practical Information" %} {% fa6_icon 'info' %}
                </a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'website:trips' %}">
                  {% trans "Tips for Trips" %} {% fa6_icon 'route' %}
                </a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'website:gallery' %}">
                  {% trans "Photo Gallery" %} {% fa6_icon 'image' %}
                </a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'website:calendar' %}">
                  {% trans "Calendar" %} {% fa6_icon 'calendar' %}
                </a>
              </li>
              {% if user.is_superuser %}
                <li>
                  <a class="nav-item nav-link" href="{% url 'admin:index' %}">
                    {% trans "Administration" %} {% fa6_icon 'cog' %}
                  </a>
                </li>
              {% endif %}
            </ul>
          {% endactiveurl %}
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/accounts/logout">
              {% trans "Logout" %} {% fa6_icon 'sign-out' %}
            </a>
          </div>
          </div>
        </nav>
      </div>
      <div class="card-body">
        <img class="mw-100" src="{% header_image %}" alt="Banner" />
      </div>
      <div class="card-body">
        <main role="main">
          {% block content %}
          {% endblock %}
        </main>
      </div>
      <div class="card-body">
        <div class="footer container mb-2">
          <div class="float-right">
            <a href="http://www.djangoproject.com/">
              <img src="https://www.djangoproject.com/m/img/badges/djangomade124x25_grey.gif" border="0" alt="Made with Django." title="Made with Django." />
            </a>
          </div>
        </div>
      </div>
    </div>
    <form action="{% url 'set_language' %}" method="post" id="lang-form" class="d-none">
      {% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}" />
      <input name="language" type="hidden" />
      <input type="submit" />
    </form>
    {% block endbody %}
    {% endblock %}
  </body>
{% endblock %}